### ISSUE TITLE
URL of Custom URL nav item loses it's value after editing the nav item

### ISSUE THREAD

**Issue by frontedbe** [verbb/navigation#226]
**Description**
URL of Custom URL nav item loses it's value after editing the nav item
[View screenvideo](https://share.getcloudapp.com/E0u4qmPk)

**Additional info**
- Plugin version: 1.4.5
- Craft version: 3.5.16
- Multi-site: Yes
- Propagate nodes: Yes

**Comment by tyssen** [comment]
I've just come across this too. My setup is Navigation 1.4.5 and Craft 3.5.11.1.

**Comment by engram-design** [comment]
Fixed in [1.4.6](https://github.com/verbb/navigation/releases/tag/1.4.6)

**Comment by tyssen** [comment]
Still occurring for me. Steps to reproduce:

1. Create a Custom URL item and it saves successfully
2. Edit the item and add text to a subheading field that I added to the node fields layout
3. When I edit the item again, the URL is gone

**Comment by engram-design** [comment]
You're totally right, sorry about that. See [1.4.7](https://github.com/verbb/navigation/releases/tag/1.4.7)
